### Read all films with File variable
GET http://localhost:3000/films

###  Read one film 
GET http://localhost:3000/films/4

###create a new film 
POST http://localhost:3000/films
Content-Type: application/json

{
    "title" : "Miendji le Super Heros 3D" ,
    "director" : "Tchuini Christian" ,
    "duration" : 192

}

### Read all filtered
GET http://localhost:3000/films/?minimun-duration=148

### Read a filter with title starting
GET http://localhost:3000/films/?starts-with=Para

###   Sorting our films table
GET http://localhost:3000/films/?sort-by=budget&order=asc