### Read all films with File variable
GET http://localhost:3000/films

###  Read one film 
GET http://localhost:3000/films/4

###create a new film 
POST http://localhost:3000/films
Content-Type: application/json

{
    "title" : "Miendji le Super Heros 3D" ,
    "director" : "Tchuini Christian" ,
    "duration" : 192

}

### Read all filtered
GET http://localhost:3000/films/?minimun-duration=148

### Read a filter with title starting
GET http://localhost:3000/films/?starts-with=Para

###   Sorting our films table
GET http://localhost:3000/films/?sort-by=budget&order=asc

### Update the drink identified by 5
PATCH http://localhost:3000/films/2
Content-Type:  : application/json

{
    "title":"Guerrier Galaxy Warrior"
}

### Delete one film
DELETE http://localhost:3000/films/1

###Put a movies
PUT http://localhost:3000/films/5
Content-Type: application/json

{
    "title" : "Forest-Gun",
    "director" : "Paul-Gerad",
    "duration" : 127,
    "budget": 189,
    "imageUrl" :"https://sekai.one/",
    "description": "https://www.bing.com/search?q=forest&qs=n&form=QBRE&sp=-1&lq=0&pq=forest&sc=12-6&sk=&cvid=A7A0182CDF8348F2A659BDAA929D055E"
}